services:

  base-py310:
    image: eedro-base-py310
    build:
      network: host
      dockerfile: ci/base/Dockerfile
      args:
        PYTHON_VERSION: "3.10"

  base-py311:
    image: eedro-base-py311
    build:
      network: host
      dockerfile: ci/base/Dockerfile
      args:
        PYTHON_VERSION: "3.11"

  base-py312:
    image: eedro-base-py312
    build:
      network: host
      dockerfile: ci/base/Dockerfile
      args:
        PYTHON_VERSION: "3.12"
