services:

  nginx:
    volumes:
      - ./ci/nginx/templates:/etc/nginx/templates

  ping:
    volumes:
      - ./:/app/src

  pong:
    volumes:
      - ./:/app/src

  cli:
    volumes:
      - ./:/app/src

  tests:
    image: $%{project_name}-tests
    build:
      network: host
      dockerfile: ci/tests/Dockerfile
      additional_contexts:
        $%{project_name}-base: "service:base"
    command: /bin/bash /app/src/ci/tests/run.sh
    volumes:
      - ./:/app/src
    depends_on:
      - base
      - nginx
